// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ROVprotocol.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ROVprotocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ControlPacket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ControlPacket_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ROVprotocol_2eproto() {
  protobuf_AddDesc_ROVprotocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ROVprotocol.proto");
  GOOGLE_CHECK(file != NULL);
  ControlPacket_descriptor_ = file->message_type(0);
  static const int ControlPacket_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster5_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster6_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster7_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, thruster8_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, claw_on_),
  };
  ControlPacket_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ControlPacket_descriptor_,
      ControlPacket::default_instance_,
      ControlPacket_offsets_,
      -1,
      -1,
      -1,
      sizeof(ControlPacket),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ControlPacket, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ROVprotocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ControlPacket_descriptor_, &ControlPacket::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ROVprotocol_2eproto() {
  delete ControlPacket::default_instance_;
  delete ControlPacket_reflection_;
}

void protobuf_AddDesc_ROVprotocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021ROVprotocol.proto\"\270\001\n\rControlPacket\022\021\n"
    "\tthruster1\030\001 \003(\005\022\021\n\tthruster2\030\002 \003(\005\022\021\n\tt"
    "hruster3\030\003 \003(\005\022\021\n\tthruster4\030\004 \003(\005\022\021\n\tthr"
    "uster5\030\005 \003(\005\022\021\n\tthruster6\030\006 \003(\005\022\021\n\tthrus"
    "ter7\030\007 \003(\005\022\021\n\tthruster8\030\010 \003(\005\022\017\n\007claw_on"
    "\030\t \003(\010b\006proto3", 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ROVprotocol.proto", &protobuf_RegisterTypes);
  ControlPacket::default_instance_ = new ControlPacket();
  ControlPacket::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ROVprotocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ROVprotocol_2eproto {
  StaticDescriptorInitializer_ROVprotocol_2eproto() {
    protobuf_AddDesc_ROVprotocol_2eproto();
  }
} static_descriptor_initializer_ROVprotocol_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ControlPacket::kThruster1FieldNumber;
const int ControlPacket::kThruster2FieldNumber;
const int ControlPacket::kThruster3FieldNumber;
const int ControlPacket::kThruster4FieldNumber;
const int ControlPacket::kThruster5FieldNumber;
const int ControlPacket::kThruster6FieldNumber;
const int ControlPacket::kThruster7FieldNumber;
const int ControlPacket::kThruster8FieldNumber;
const int ControlPacket::kClawOnFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ControlPacket::ControlPacket()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ControlPacket)
}

void ControlPacket::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ControlPacket::ControlPacket(const ControlPacket& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ControlPacket)
}

void ControlPacket::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ControlPacket::~ControlPacket() {
  // @@protoc_insertion_point(destructor:ControlPacket)
  SharedDtor();
}

void ControlPacket::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ControlPacket::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ControlPacket::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ControlPacket_descriptor_;
}

const ControlPacket& ControlPacket::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ROVprotocol_2eproto();
  return *default_instance_;
}

ControlPacket* ControlPacket::default_instance_ = NULL;

ControlPacket* ControlPacket::New(::google::protobuf::Arena* arena) const {
  ControlPacket* n = new ControlPacket;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ControlPacket::Clear() {
  thruster1_.Clear();
  thruster2_.Clear();
  thruster3_.Clear();
  thruster4_.Clear();
  thruster5_.Clear();
  thruster6_.Clear();
  thruster7_.Clear();
  thruster8_.Clear();
  claw_on_.Clear();
}

bool ControlPacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ControlPacket)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 thruster1 = 1;
      case 1: {
        if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster1())));
        } else if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10, input, this->mutable_thruster1())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_thruster2;
        break;
      }

      // repeated int32 thruster2 = 2;
      case 2: {
        if (tag == 18) {
         parse_thruster2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster2())));
        } else if (tag == 16) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18, input, this->mutable_thruster2())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_thruster3;
        break;
      }

      // repeated int32 thruster3 = 3;
      case 3: {
        if (tag == 26) {
         parse_thruster3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster3())));
        } else if (tag == 24) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26, input, this->mutable_thruster3())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_thruster4;
        break;
      }

      // repeated int32 thruster4 = 4;
      case 4: {
        if (tag == 34) {
         parse_thruster4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster4())));
        } else if (tag == 32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 34, input, this->mutable_thruster4())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_thruster5;
        break;
      }

      // repeated int32 thruster5 = 5;
      case 5: {
        if (tag == 42) {
         parse_thruster5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster5())));
        } else if (tag == 40) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 42, input, this->mutable_thruster5())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_thruster6;
        break;
      }

      // repeated int32 thruster6 = 6;
      case 6: {
        if (tag == 50) {
         parse_thruster6:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster6())));
        } else if (tag == 48) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 50, input, this->mutable_thruster6())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_thruster7;
        break;
      }

      // repeated int32 thruster7 = 7;
      case 7: {
        if (tag == 58) {
         parse_thruster7:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster7())));
        } else if (tag == 56) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 58, input, this->mutable_thruster7())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_thruster8;
        break;
      }

      // repeated int32 thruster8 = 8;
      case 8: {
        if (tag == 66) {
         parse_thruster8:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_thruster8())));
        } else if (tag == 64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 66, input, this->mutable_thruster8())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_claw_on;
        break;
      }

      // repeated bool claw_on = 9;
      case 9: {
        if (tag == 74) {
         parse_claw_on:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_claw_on())));
        } else if (tag == 72) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 74, input, this->mutable_claw_on())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ControlPacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ControlPacket)
  return false;
#undef DO_
}

void ControlPacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ControlPacket)
  // repeated int32 thruster1 = 1;
  if (this->thruster1_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster1_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster1_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster1(i), output);
  }

  // repeated int32 thruster2 = 2;
  if (this->thruster2_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster2_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster2_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster2(i), output);
  }

  // repeated int32 thruster3 = 3;
  if (this->thruster3_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster3_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster3_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster3(i), output);
  }

  // repeated int32 thruster4 = 4;
  if (this->thruster4_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster4_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster4_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster4(i), output);
  }

  // repeated int32 thruster5 = 5;
  if (this->thruster5_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster5_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster5_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster5(i), output);
  }

  // repeated int32 thruster6 = 6;
  if (this->thruster6_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster6_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster6_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster6(i), output);
  }

  // repeated int32 thruster7 = 7;
  if (this->thruster7_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(7, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster7_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster7_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster7(i), output);
  }

  // repeated int32 thruster8 = 8;
  if (this->thruster8_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(8, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_thruster8_cached_byte_size_);
  }
  for (int i = 0; i < this->thruster8_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->thruster8(i), output);
  }

  // repeated bool claw_on = 9;
  if (this->claw_on_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(9, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_claw_on_cached_byte_size_);
  }
  for (int i = 0; i < this->claw_on_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBoolNoTag(
      this->claw_on(i), output);
  }

  // @@protoc_insertion_point(serialize_end:ControlPacket)
}

::google::protobuf::uint8* ControlPacket::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ControlPacket)
  // repeated int32 thruster1 = 1;
  if (this->thruster1_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster1_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster1_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster1(i), target);
  }

  // repeated int32 thruster2 = 2;
  if (this->thruster2_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster2_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster2_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster2(i), target);
  }

  // repeated int32 thruster3 = 3;
  if (this->thruster3_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster3_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster3_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster3(i), target);
  }

  // repeated int32 thruster4 = 4;
  if (this->thruster4_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster4_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster4_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster4(i), target);
  }

  // repeated int32 thruster5 = 5;
  if (this->thruster5_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster5_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster5_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster5(i), target);
  }

  // repeated int32 thruster6 = 6;
  if (this->thruster6_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster6_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster6_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster6(i), target);
  }

  // repeated int32 thruster7 = 7;
  if (this->thruster7_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      7,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster7_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster7_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster7(i), target);
  }

  // repeated int32 thruster8 = 8;
  if (this->thruster8_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      8,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _thruster8_cached_byte_size_, target);
  }
  for (int i = 0; i < this->thruster8_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->thruster8(i), target);
  }

  // repeated bool claw_on = 9;
  if (this->claw_on_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      9,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _claw_on_cached_byte_size_, target);
  }
  for (int i = 0; i < this->claw_on_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolNoTagToArray(this->claw_on(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ControlPacket)
  return target;
}

int ControlPacket::ByteSize() const {
  int total_size = 0;

  // repeated int32 thruster1 = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster1_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster1(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster1_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster2 = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster2_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster2(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster2_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster3 = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster3_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster3(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster3_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster4 = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster4_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster4(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster4_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster5 = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster5_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster5(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster5_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster6 = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster6_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster6(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster6_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster7 = 7;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster7_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster7(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster7_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 thruster8 = 8;
  {
    int data_size = 0;
    for (int i = 0; i < this->thruster8_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->thruster8(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _thruster8_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated bool claw_on = 9;
  {
    int data_size = 0;
    data_size = 1 * this->claw_on_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _claw_on_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ControlPacket::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ControlPacket* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ControlPacket>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ControlPacket::MergeFrom(const ControlPacket& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  thruster1_.MergeFrom(from.thruster1_);
  thruster2_.MergeFrom(from.thruster2_);
  thruster3_.MergeFrom(from.thruster3_);
  thruster4_.MergeFrom(from.thruster4_);
  thruster5_.MergeFrom(from.thruster5_);
  thruster6_.MergeFrom(from.thruster6_);
  thruster7_.MergeFrom(from.thruster7_);
  thruster8_.MergeFrom(from.thruster8_);
  claw_on_.MergeFrom(from.claw_on_);
}

void ControlPacket::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlPacket::CopyFrom(const ControlPacket& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlPacket::IsInitialized() const {

  return true;
}

void ControlPacket::Swap(ControlPacket* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ControlPacket::InternalSwap(ControlPacket* other) {
  thruster1_.UnsafeArenaSwap(&other->thruster1_);
  thruster2_.UnsafeArenaSwap(&other->thruster2_);
  thruster3_.UnsafeArenaSwap(&other->thruster3_);
  thruster4_.UnsafeArenaSwap(&other->thruster4_);
  thruster5_.UnsafeArenaSwap(&other->thruster5_);
  thruster6_.UnsafeArenaSwap(&other->thruster6_);
  thruster7_.UnsafeArenaSwap(&other->thruster7_);
  thruster8_.UnsafeArenaSwap(&other->thruster8_);
  claw_on_.UnsafeArenaSwap(&other->claw_on_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ControlPacket::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ControlPacket_descriptor_;
  metadata.reflection = ControlPacket_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ControlPacket

// repeated int32 thruster1 = 1;
int ControlPacket::thruster1_size() const {
  return thruster1_.size();
}
void ControlPacket::clear_thruster1() {
  thruster1_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster1(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster1)
  return thruster1_.Get(index);
}
 void ControlPacket::set_thruster1(int index, ::google::protobuf::int32 value) {
  thruster1_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster1)
}
 void ControlPacket::add_thruster1(::google::protobuf::int32 value) {
  thruster1_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster1)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster1() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster1)
  return thruster1_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster1() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster1)
  return &thruster1_;
}

// repeated int32 thruster2 = 2;
int ControlPacket::thruster2_size() const {
  return thruster2_.size();
}
void ControlPacket::clear_thruster2() {
  thruster2_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster2(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster2)
  return thruster2_.Get(index);
}
 void ControlPacket::set_thruster2(int index, ::google::protobuf::int32 value) {
  thruster2_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster2)
}
 void ControlPacket::add_thruster2(::google::protobuf::int32 value) {
  thruster2_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster2)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster2() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster2)
  return thruster2_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster2() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster2)
  return &thruster2_;
}

// repeated int32 thruster3 = 3;
int ControlPacket::thruster3_size() const {
  return thruster3_.size();
}
void ControlPacket::clear_thruster3() {
  thruster3_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster3(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster3)
  return thruster3_.Get(index);
}
 void ControlPacket::set_thruster3(int index, ::google::protobuf::int32 value) {
  thruster3_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster3)
}
 void ControlPacket::add_thruster3(::google::protobuf::int32 value) {
  thruster3_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster3)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster3() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster3)
  return thruster3_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster3() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster3)
  return &thruster3_;
}

// repeated int32 thruster4 = 4;
int ControlPacket::thruster4_size() const {
  return thruster4_.size();
}
void ControlPacket::clear_thruster4() {
  thruster4_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster4(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster4)
  return thruster4_.Get(index);
}
 void ControlPacket::set_thruster4(int index, ::google::protobuf::int32 value) {
  thruster4_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster4)
}
 void ControlPacket::add_thruster4(::google::protobuf::int32 value) {
  thruster4_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster4)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster4() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster4)
  return thruster4_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster4() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster4)
  return &thruster4_;
}

// repeated int32 thruster5 = 5;
int ControlPacket::thruster5_size() const {
  return thruster5_.size();
}
void ControlPacket::clear_thruster5() {
  thruster5_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster5(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster5)
  return thruster5_.Get(index);
}
 void ControlPacket::set_thruster5(int index, ::google::protobuf::int32 value) {
  thruster5_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster5)
}
 void ControlPacket::add_thruster5(::google::protobuf::int32 value) {
  thruster5_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster5)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster5() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster5)
  return thruster5_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster5() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster5)
  return &thruster5_;
}

// repeated int32 thruster6 = 6;
int ControlPacket::thruster6_size() const {
  return thruster6_.size();
}
void ControlPacket::clear_thruster6() {
  thruster6_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster6(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster6)
  return thruster6_.Get(index);
}
 void ControlPacket::set_thruster6(int index, ::google::protobuf::int32 value) {
  thruster6_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster6)
}
 void ControlPacket::add_thruster6(::google::protobuf::int32 value) {
  thruster6_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster6)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster6() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster6)
  return thruster6_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster6() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster6)
  return &thruster6_;
}

// repeated int32 thruster7 = 7;
int ControlPacket::thruster7_size() const {
  return thruster7_.size();
}
void ControlPacket::clear_thruster7() {
  thruster7_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster7(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster7)
  return thruster7_.Get(index);
}
 void ControlPacket::set_thruster7(int index, ::google::protobuf::int32 value) {
  thruster7_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster7)
}
 void ControlPacket::add_thruster7(::google::protobuf::int32 value) {
  thruster7_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster7)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster7() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster7)
  return thruster7_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster7() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster7)
  return &thruster7_;
}

// repeated int32 thruster8 = 8;
int ControlPacket::thruster8_size() const {
  return thruster8_.size();
}
void ControlPacket::clear_thruster8() {
  thruster8_.Clear();
}
 ::google::protobuf::int32 ControlPacket::thruster8(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster8)
  return thruster8_.Get(index);
}
 void ControlPacket::set_thruster8(int index, ::google::protobuf::int32 value) {
  thruster8_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster8)
}
 void ControlPacket::add_thruster8(::google::protobuf::int32 value) {
  thruster8_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster8)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster8() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster8)
  return thruster8_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster8() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster8)
  return &thruster8_;
}

// repeated bool claw_on = 9;
int ControlPacket::claw_on_size() const {
  return claw_on_.size();
}
void ControlPacket::clear_claw_on() {
  claw_on_.Clear();
}
 bool ControlPacket::claw_on(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.claw_on)
  return claw_on_.Get(index);
}
 void ControlPacket::set_claw_on(int index, bool value) {
  claw_on_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.claw_on)
}
 void ControlPacket::add_claw_on(bool value) {
  claw_on_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.claw_on)
}
 const ::google::protobuf::RepeatedField< bool >&
ControlPacket::claw_on() const {
  // @@protoc_insertion_point(field_list:ControlPacket.claw_on)
  return claw_on_;
}
 ::google::protobuf::RepeatedField< bool >*
ControlPacket::mutable_claw_on() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.claw_on)
  return &claw_on_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
