// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ROVprotocol.proto

#ifndef PROTOBUF_ROVprotocol_2eproto__INCLUDED
#define PROTOBUF_ROVprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ROVprotocol_2eproto();
void protobuf_AssignDesc_ROVprotocol_2eproto();
void protobuf_ShutdownFile_ROVprotocol_2eproto();

class ControlPacket;

// ===================================================================

class ControlPacket : public ::google::protobuf::Message {
 public:
  ControlPacket();
  virtual ~ControlPacket();

  ControlPacket(const ControlPacket& from);

  inline ControlPacket& operator=(const ControlPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlPacket& default_instance();

  void Swap(ControlPacket* other);

  // implements Message ----------------------------------------------

  inline ControlPacket* New() const { return New(NULL); }

  ControlPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ControlPacket& from);
  void MergeFrom(const ControlPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ControlPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 thruster1 = 1;
  int thruster1_size() const;
  void clear_thruster1();
  static const int kThruster1FieldNumber = 1;
  ::google::protobuf::int32 thruster1(int index) const;
  void set_thruster1(int index, ::google::protobuf::int32 value);
  void add_thruster1(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster1() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster1();

  // repeated int32 thruster2 = 2;
  int thruster2_size() const;
  void clear_thruster2();
  static const int kThruster2FieldNumber = 2;
  ::google::protobuf::int32 thruster2(int index) const;
  void set_thruster2(int index, ::google::protobuf::int32 value);
  void add_thruster2(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster2() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster2();

  // repeated int32 thruster3 = 3;
  int thruster3_size() const;
  void clear_thruster3();
  static const int kThruster3FieldNumber = 3;
  ::google::protobuf::int32 thruster3(int index) const;
  void set_thruster3(int index, ::google::protobuf::int32 value);
  void add_thruster3(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster3() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster3();

  // repeated int32 thruster4 = 4;
  int thruster4_size() const;
  void clear_thruster4();
  static const int kThruster4FieldNumber = 4;
  ::google::protobuf::int32 thruster4(int index) const;
  void set_thruster4(int index, ::google::protobuf::int32 value);
  void add_thruster4(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster4() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster4();

  // repeated int32 thruster5 = 5;
  int thruster5_size() const;
  void clear_thruster5();
  static const int kThruster5FieldNumber = 5;
  ::google::protobuf::int32 thruster5(int index) const;
  void set_thruster5(int index, ::google::protobuf::int32 value);
  void add_thruster5(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster5() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster5();

  // repeated int32 thruster6 = 6;
  int thruster6_size() const;
  void clear_thruster6();
  static const int kThruster6FieldNumber = 6;
  ::google::protobuf::int32 thruster6(int index) const;
  void set_thruster6(int index, ::google::protobuf::int32 value);
  void add_thruster6(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster6() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster6();

  // repeated int32 thruster7 = 7;
  int thruster7_size() const;
  void clear_thruster7();
  static const int kThruster7FieldNumber = 7;
  ::google::protobuf::int32 thruster7(int index) const;
  void set_thruster7(int index, ::google::protobuf::int32 value);
  void add_thruster7(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster7() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster7();

  // repeated int32 thruster8 = 8;
  int thruster8_size() const;
  void clear_thruster8();
  static const int kThruster8FieldNumber = 8;
  ::google::protobuf::int32 thruster8(int index) const;
  void set_thruster8(int index, ::google::protobuf::int32 value);
  void add_thruster8(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      thruster8() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_thruster8();

  // repeated bool claw_on = 9;
  int claw_on_size() const;
  void clear_claw_on();
  static const int kClawOnFieldNumber = 9;
  bool claw_on(int index) const;
  void set_claw_on(int index, bool value);
  void add_claw_on(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      claw_on() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_claw_on();

  // @@protoc_insertion_point(class_scope:ControlPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster1_;
  mutable int _thruster1_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster2_;
  mutable int _thruster2_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster3_;
  mutable int _thruster3_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster4_;
  mutable int _thruster4_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster5_;
  mutable int _thruster5_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster6_;
  mutable int _thruster6_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster7_;
  mutable int _thruster7_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > thruster8_;
  mutable int _thruster8_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > claw_on_;
  mutable int _claw_on_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ROVprotocol_2eproto();
  friend void protobuf_AssignDesc_ROVprotocol_2eproto();
  friend void protobuf_ShutdownFile_ROVprotocol_2eproto();

  void InitAsDefaultInstance();
  static ControlPacket* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ControlPacket

// repeated int32 thruster1 = 1;
inline int ControlPacket::thruster1_size() const {
  return thruster1_.size();
}
inline void ControlPacket::clear_thruster1() {
  thruster1_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster1(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster1)
  return thruster1_.Get(index);
}
inline void ControlPacket::set_thruster1(int index, ::google::protobuf::int32 value) {
  thruster1_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster1)
}
inline void ControlPacket::add_thruster1(::google::protobuf::int32 value) {
  thruster1_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster1)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster1() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster1)
  return thruster1_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster1() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster1)
  return &thruster1_;
}

// repeated int32 thruster2 = 2;
inline int ControlPacket::thruster2_size() const {
  return thruster2_.size();
}
inline void ControlPacket::clear_thruster2() {
  thruster2_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster2(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster2)
  return thruster2_.Get(index);
}
inline void ControlPacket::set_thruster2(int index, ::google::protobuf::int32 value) {
  thruster2_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster2)
}
inline void ControlPacket::add_thruster2(::google::protobuf::int32 value) {
  thruster2_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster2)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster2() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster2)
  return thruster2_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster2() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster2)
  return &thruster2_;
}

// repeated int32 thruster3 = 3;
inline int ControlPacket::thruster3_size() const {
  return thruster3_.size();
}
inline void ControlPacket::clear_thruster3() {
  thruster3_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster3(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster3)
  return thruster3_.Get(index);
}
inline void ControlPacket::set_thruster3(int index, ::google::protobuf::int32 value) {
  thruster3_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster3)
}
inline void ControlPacket::add_thruster3(::google::protobuf::int32 value) {
  thruster3_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster3)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster3() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster3)
  return thruster3_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster3() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster3)
  return &thruster3_;
}

// repeated int32 thruster4 = 4;
inline int ControlPacket::thruster4_size() const {
  return thruster4_.size();
}
inline void ControlPacket::clear_thruster4() {
  thruster4_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster4(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster4)
  return thruster4_.Get(index);
}
inline void ControlPacket::set_thruster4(int index, ::google::protobuf::int32 value) {
  thruster4_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster4)
}
inline void ControlPacket::add_thruster4(::google::protobuf::int32 value) {
  thruster4_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster4)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster4() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster4)
  return thruster4_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster4() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster4)
  return &thruster4_;
}

// repeated int32 thruster5 = 5;
inline int ControlPacket::thruster5_size() const {
  return thruster5_.size();
}
inline void ControlPacket::clear_thruster5() {
  thruster5_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster5(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster5)
  return thruster5_.Get(index);
}
inline void ControlPacket::set_thruster5(int index, ::google::protobuf::int32 value) {
  thruster5_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster5)
}
inline void ControlPacket::add_thruster5(::google::protobuf::int32 value) {
  thruster5_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster5)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster5() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster5)
  return thruster5_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster5() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster5)
  return &thruster5_;
}

// repeated int32 thruster6 = 6;
inline int ControlPacket::thruster6_size() const {
  return thruster6_.size();
}
inline void ControlPacket::clear_thruster6() {
  thruster6_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster6(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster6)
  return thruster6_.Get(index);
}
inline void ControlPacket::set_thruster6(int index, ::google::protobuf::int32 value) {
  thruster6_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster6)
}
inline void ControlPacket::add_thruster6(::google::protobuf::int32 value) {
  thruster6_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster6)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster6() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster6)
  return thruster6_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster6() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster6)
  return &thruster6_;
}

// repeated int32 thruster7 = 7;
inline int ControlPacket::thruster7_size() const {
  return thruster7_.size();
}
inline void ControlPacket::clear_thruster7() {
  thruster7_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster7(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster7)
  return thruster7_.Get(index);
}
inline void ControlPacket::set_thruster7(int index, ::google::protobuf::int32 value) {
  thruster7_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster7)
}
inline void ControlPacket::add_thruster7(::google::protobuf::int32 value) {
  thruster7_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster7)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster7() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster7)
  return thruster7_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster7() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster7)
  return &thruster7_;
}

// repeated int32 thruster8 = 8;
inline int ControlPacket::thruster8_size() const {
  return thruster8_.size();
}
inline void ControlPacket::clear_thruster8() {
  thruster8_.Clear();
}
inline ::google::protobuf::int32 ControlPacket::thruster8(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.thruster8)
  return thruster8_.Get(index);
}
inline void ControlPacket::set_thruster8(int index, ::google::protobuf::int32 value) {
  thruster8_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.thruster8)
}
inline void ControlPacket::add_thruster8(::google::protobuf::int32 value) {
  thruster8_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.thruster8)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ControlPacket::thruster8() const {
  // @@protoc_insertion_point(field_list:ControlPacket.thruster8)
  return thruster8_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ControlPacket::mutable_thruster8() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.thruster8)
  return &thruster8_;
}

// repeated bool claw_on = 9;
inline int ControlPacket::claw_on_size() const {
  return claw_on_.size();
}
inline void ControlPacket::clear_claw_on() {
  claw_on_.Clear();
}
inline bool ControlPacket::claw_on(int index) const {
  // @@protoc_insertion_point(field_get:ControlPacket.claw_on)
  return claw_on_.Get(index);
}
inline void ControlPacket::set_claw_on(int index, bool value) {
  claw_on_.Set(index, value);
  // @@protoc_insertion_point(field_set:ControlPacket.claw_on)
}
inline void ControlPacket::add_claw_on(bool value) {
  claw_on_.Add(value);
  // @@protoc_insertion_point(field_add:ControlPacket.claw_on)
}
inline const ::google::protobuf::RepeatedField< bool >&
ControlPacket::claw_on() const {
  // @@protoc_insertion_point(field_list:ControlPacket.claw_on)
  return claw_on_;
}
inline ::google::protobuf::RepeatedField< bool >*
ControlPacket::mutable_claw_on() {
  // @@protoc_insertion_point(field_mutable_list:ControlPacket.claw_on)
  return &claw_on_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ROVprotocol_2eproto__INCLUDED
